### ISSUE TITLE
(WALLC-S) Installation halts on "retreiving multi channel nodes"

### ISSUE THREAD

**Issue by bm480** [IcarusProject/me.zwave#11] opened 2017-02-02 06:38 UTC
(WALLC-S) Installation halts on "retreiving multi channel nodes" and starts from the beginning by asking to press on of the 4 buttons. Am I doing something wrong?

**Comment by Tweaqer** [comment] 2017-02-07 16:27
+1 for this problem

**Comment by fransklerks** [comment] 2017-02-19 17:05
also +1
Systeem Informatie:
Homey Firmware Versie: 1.1.9
Z-Wave.Me v0.0.11 Icarus....

Multi channel nodes worden opgehaald
Restarts to the beginning asking me to press one of 4 buttons...
unable to find a solution..
Please advise what to do..

many thnx in advance for your hard work...

Frans Klerks

**Comment by bm480** [comment] 2017-02-20 18:08
Systeem Informatie
Homey Firmware Versie: 1.1.9

Issue still not resolved. I can see leds blinking on the WALLC-S for a few seconds when "retrieving multi channel nodes" is displayed. After the blinking stops, about 10 seconds later the pairing process is restarted without the device being added to the devices list.

The Z-Wave pairing seems to have succeeded however, I can see the node in the new Z-Wave for Geeks window. Also, before retrying I have to unpair via the Z-Wave window.

**Comment by fransklerks** [comment] 2017-02-22 12:26
Annermarie Moderator Athom, has reacted in this thread...

https://forum.athom.com/discussion/comment/46498/#Comment_46498

**Comment by RobinBol** [comment] 2017-03-02 15:35
We found the cause of this issue, it will be fixed in an upcoming Homey firmware update!

The devices that keep hanging on retrieving multichannel nodes seem to use COMMAND_CLASS_MULTI_CHANNEL V1 which is not used/supported anymore.

**Comment by fransklerks** [comment] 2017-03-02 15:40
Hai Robin,

 

Many thanks.

 

Can you tell me when the next firmware update will be?

 

Greetz Frans Klerks

 

Van: Robin Bolscher [mailto:notifications@github.com] 
Verzonden: donderdag 2 maart 2017 16:35
Aan: IcarusProject/me.zwave <me.zwave@noreply.github.com>
CC: fransklerks <klerks@home.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [IcarusProject/me.zwave] (WALLC-S) Installation halts on "retreiving multi channel nodes" (#11)

 

We found the cause of this issue, it will be fixed in an upcoming Homey firmware update!

The devices that keep hanging on retrieving multichannel nodes seem to use COMMAND_CLASS_MULTI_CHANNEL V1 which is not used/supported anymore.

**Comment by IcarusProject** [comment] 2017-03-21 10:42
Problem seems to be solved by changes in the Homey source.

**Closed by IcarusProject** 2017-03-21 10:42 UTC
